### ISSUE TITLE
Add logic to create flow logs in terraform-ibm-landing-zone-vpc module

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#379]
### Description

The flow log creation logic conceptually belong to this VPC module.
The logic is currently located in the landing-zone module (at https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/main.tf#L39)

The objective of this ticket is to:
1. Move the flow log logic to this VPC module
2. Update the references in the landing-zone module

### New or affected modules

- terraform-ibm-landing-zone-vpc 
- terraform-ibm-landing-zone

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Tracking the second part of this in SLZ repo https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/403 and closing this issue as all the dev work for VPC flow log logic has been completed in this module
