### ISSUE TITLE
Create submodules with defaults aligned with landing-zone workload and management VPCs

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#380]
### Description

Context:
- The patterns at https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone currently pass parameters to this vpc module to create 2 types of VPCs: workload and management VPCs. This example https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/tree/main/examples/no-compute-example creates the 2 type of VPCs
- Some consumers want to use the VPC module directly to gain extra flexibility
- The VPC module contains generic defaults currently (eg: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/blob/main/variables.tf#L256)

What:
- The objective of this ticket is to create 2 submodules (1 for workload and 1 for management VPC) that call the parent module with the right input variables / defaults to create a workload and management vpcs aligned with what is being passed by the https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone currently.

### New or affected modules

- [terraform-ibm-landing-zone-vpc](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aashiq-J** [comment]
PR merged. closing issue
