### ISSUE TITLE
Add subnet output designed to work OOTB with the ocp-base module

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#399]
Description

See https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/15#discussion_r1118594503

I think we should add an output designed to be consumed by the ocp module in the vpc module to ease integration between the 2 modules.
New or affected modules

    terraform-ibm-base-ocp-vpc module

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by imprateeksh** [comment]
Changes are merged. Marking the issue as closed.
