### ISSUE TITLE
Terraform error creating outputs with v5.0.0

### ISSUE THREAD

**Issue by irizzant** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#443]
I'm trying to run `terraform plan` on this module after upgrading to v5.0.0 and I get an error which I didn't get before.
I have the following vars:
```
address_prefixes = {
    zone-1 = ["10.243.0.0/23", "10.243.5.0/24"]
    zone-2 = ["10.243.64.0/23", "10.243.69.0/24"]
    zone-3 = ["10.243.128.0/23", "10.243.133.0/24"]
  }
```

and my `subnets` is an object with 6 subnets (2 for each zone).

When I run `terraform plan` I get the error reported below, which was probably introduced in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/427

`ibm_is_subnet.subnet` contains 6 items but `var.address_prefixes` is an object with some lists in it, so it only contains 3 items
 

### Affected modules

* [terraform-ibm-landing-zone-vpc](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc)

### Terraform CLI and Terraform provider versions

Terraform v1.4.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.51.0

### Expected behavior

I should be able to run `terraform plan` on the module.

### Actual behavior

I get the following error:
```│ Error: Error in function call
│ 
│   on .terraform/modules/vpc/outputs.tf line 83, in output "subnet_detail_map":
│   83:   value       = zipmap([for prefix, _ in var.address_prefixes : prefix], [for subnet in ibm_is_subnet.subnet : [{ id = subnet.id, zone = subnet.zone, cidr_block = subnet.ipv4_cidr_block }]])
│     ├────────────────
│     │ while calling zipmap(keys, values)
│     │ ibm_is_subnet.subnet is object with 6 attributes
│     │ var.address_prefixes is object with 3 attributes
│ 
│ Call to function "zipmap" failed: number of keys (3) does not match number of values (6).`

### Steps to reproduce (including links and screen captures)

<!-- List the steps required to reproduce the issue. -->

1. Run `terraform apply`

### Anything else

<!-- Include anything that will give us more context about the issue. -->

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aashiq-J** [comment]
Fix merged. Closing issue. Thanks
