### ISSUE TITLE
cleanup: remove unexercised logic under dynamic_values

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#486]
### Description

There is significant amount of legacy logic under the dynamic_values folder. However, only a small subset of those are used at the moment - see https://github.com/search?q=repo%3Aterraform-ibm-modules%2Fterraform-ibm-landing-zone-vpc+module.dynamic_values&type=code

This ticket is about removing the unused logic for now to avoid any confusion.

**Comment by maheshwarishikha** [comment]
Merged the changes through issue 4376. Closing the issue.
