### ISSUE TITLE
Create a basic VPC example

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#591]
### Description

It may be good to have a very basic example. The current examples creates relatively complex topology.

Something like: VPC with 1 subnet that is publically exposed (public gw, default VPC network acl).

**Comment by rajatagarwal-ibm** [comment]
Implemented - closing this issue.

**Comment by vburckhardt** [comment]
We may need to review - the basic example is creating multiple subnets.

**Comment by ocofaigh** [comment]
Addressed in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/670
