### ISSUE TITLE
Need a support for existing VPC functionality

### ISSUE THREAD

**Issue by digvijay-ukirde** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#599]
### Description

Customers usually have an existing VPC and expect the solution (VSIs) to be deployed in the same.
Requirements:

1. **Existing VPC**: If the customer provides a VPC name, we should not create VPC and address prefix (default=null); and use the VPC to deploy the resources (subnet, VSI, SG etc)
2. **Existing Subnet**: If customer provide a subnet name, we should skip Subnet creation (default=null) and use the subnet to deploy the resources (VSI, SG, Gateway etc)
3. **Existing Gateway**: If customer provide a VPC where gateway already exists for a particular zone then use it and skip creating gateway

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
- On VPC: current thinking is to see whether we could enhance landing zone module to skip vpc creation, in other word empty array in vpcs field.
   - scenario of existing vpc - enable creation of subnets / skip creation of subnets

- Expose the vsi secondary interface inputs in the landing zone module https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/02648ac36c2eb15d9bceb8c43f200c6418a38735/variables.tf#L270

**Comment by Aayush-Abhyarthi** [comment]
Currently looking for ways to use skip the vpc creation in the module so that the passed vpc can be used .

**Comment by ocofaigh** [comment]
This support was added in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/releases/tag/v7.12.0
We are now looking to see if we can add support to the SLZ solution. Tracked at https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/635
