### ISSUE TITLE
Addition of dns attributes to the vpc resource 

### ISSUE THREAD

**Issue by astha-jain** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#652]
### Description

VPC introduced new feature on vpc resource -  dns attribute. Request from BNPP is to add this attribute to the module at following location 

### New or affected modules
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/blob/main/main.tf#L24

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
Current proposal attached

![prop](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/assets/16447795/7ed6cd43-e501-4b90-a84a-117255a7ebae)
