### ISSUE TITLE
Address prefixes auto generated when specifying only subnets

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#676]
Run examples/basic. Notice that the address prefixes 10.240.64.0/18 that do not belong to the subnets.

![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/assets/16447795/96c274cd-5d99-4453-9da5-ddba2675239e)
---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Looks like Vincent created a PR for this https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/679
