### ISSUE TITLE
Incorrect About Description

### ISSUE THREAD

**Issue by PatrickDuncan** [terraform-ibm-modules/terraform-ibm-landing-zone-vpc#894]
### Affected modules

This module. https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc

---

> About
> 
> Creates virtual servers across subnets in a single VPC connected by a single security group. Supports floating IP addresses and multiple load balancers. 

This module only provides the VPC resources, there are no "virtual servers"

**Comment by arya-girish-k** [comment]
cc : @SarikaSinha

**Comment by arya-girish-k** [comment]
Merged this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/900).Closing the issue
